# Generated by Django 5.0.1 on 2024-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_billing_address_order_is_paid_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
