# Generated by Django 5.0.1 on 2024-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_order_number'),
        ('vendor', '0008_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='vendor.product'),
        ),
    ]
